modify gha workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,12 +47,24 @@ jobs:
           definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
           fails-on: 4
       
+      # - name: Expected outcomes
+      #   continue-on-error: false
+      #   if: always()
+      #   run: |
+      #     if [ "${{ steps.openapi-1.outcome }}" == "success" ] && [ "${{ steps.openapi-4.outcome }}" == "failure" ] && [ "${{ steps.openapiWithErrors-1.outcome }}" == "failure" ] && [ "${{ steps.openapiWithErrors-4.outcome }}" == "failure" ]; then
+      #       exit 0
+      #     else
+      #       exit 1
+      #     fi
+  verify_outcomes:
+    needs: test_github_action
+    runs-on: ubuntu-latest
+
       - name: Expected outcomes
-        continue-on-error: false
-        if: always()
         run: |
           if [ "${{ steps.openapi-1.outcome }}" == "success" ] && [ "${{ steps.openapi-4.outcome }}" == "failure" ] && [ "${{ steps.openapiWithErrors-1.outcome }}" == "failure" ] && [ "${{ steps.openapiWithErrors-4.outcome }}" == "failure" ]; then
             exit 0
           else
             exit 1
           fi
+   
