change gha

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -14,6 +14,7 @@ on:
 jobs:
   test_github_action:
     runs-on: ubuntu-latest
+    continue-on-error: true
     outputs:
       output1: ${{ steps.test1.outcome }}
       output2: ${{ steps.test2.outcome }}
@@ -23,30 +24,29 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: "Test 1: Validate openapi.json file at Severity level 1 (Errors)"
-        id: test1
-        continue-on-error: true
+      - id: test1
+        name: "Test 1: Validate openapi.json file at Severity level 1 (Errors)"
         uses: amandalian/apidom-validate@trigger-error-option
         with:
           definition-file: ./.github/workflows/fixtures/openapi.json
           fails-on: 1
-      - name: "Test 2: Validate openapi.json file at Severity level 4 (Hints)"
-        id: test2
-        continue-on-error: true
+      - id: test2
+        name: "Test 2: Validate openapi.json file at Severity level 4 (Hints)"
+        if: success() || failed()
         uses: amandalian/apidom-validate@trigger-error-option
         with:
           definition-file: ./.github/workflows/fixtures/openapi.json
           fails-on: 4
-      - name: "Test 3: Validate openapi_with_errors.json file at Severity level 1 (Errors)"
-        id: test3
-        continue-on-error: true
+      - id: test3
+        name: "Test 3: Validate openapi_with_errors.json file at Severity level 1 (Errors)"
+        if: success() || failed()
         uses: amandalian/apidom-validate@trigger-error-option
         with:
           definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
           fails-on: 1
-      - name: "Test 4: Validate openapi_with_errors.json file at Severity level 4 (Hints)"
-        id: test4
-        continue-on-error: true
+      - id: test4
+        name: "Test 4: Validate openapi_with_errors.json file at Severity level 4 (Hints)"
+        if: success() || failed()
         uses: amandalian/apidom-validate@trigger-error-option
         with:
           definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
@@ -68,10 +68,10 @@ jobs:
           echo "  4   | openapi_with_errors.json |        4       |      failure     |    ${{ needs.test_github_action.outputs['output4'] }}"
 
           if [ "${{ needs.test_github_action.outputs['output1'] }}" == "success" ] && [ "${{ needs.test_github_action.outputs['output2'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output3'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output4'] }}" == "failure" ]; then
-            echo "Test succeeded: Actual outcomes match expected outcomes"
+            echo "SUCCESS: Actual outcomes match expected outcomes"
             exit 0
           else
-            echo "Test failed: Actual outcomes do not match expected outcomes."
+            echo "FAILED: Actual outcomes do not match expected outcomes."
             exit 1
           fi
    
